### PR TITLE
docs: fix repetion in the comments

### PR DESCRIPTION
**Pull request by PicchiSeba**
This simple PR removes a redundant 'the' in the comments

### CODE REVIEW

**Review by slawlor — APPROVED** [review]
lgtm

**Comment by 3318356049** [comment]
<Proxy>/WhatsApp.Twilio

**Comment by Zahidosmani** [comment]
#203

**Comment by mckillopjamie66** [comment]
Hellp

**Review by K91AYAM — APPROVED** [review]

**Pull request merged**
