### PR TITLE
Resolve: Issue #54

### PR DESCRIPTION
**Pull request by nimeshkasun**
Fix for the issue https://github.com/WhatsApp/proxy/issues/54

`ENV PUBLIC_IP=YOUR_SERVER_PUBLIC_IP`

### CODE REVIEW

**Review by matinzd — COMMENTED** [review]
To set the PUBLIC_IP environment variable, pass -e PUBLIC_IP=x.x.x.x to the docker build command. It is important to note that this value should not be committed to the repository, as it may change depending on the host machine's public IP address.

**Comment by nimeshkasun** [comment]
> To set the PUBLIC_IP environment variable, pass `-e PUBLIC_IP=x.x.x.x` to the `docker build` command. It is important to note that this value should not be committed to the repository, as it may change depending on the host machine's public IP address.

So, the build command should be like below?

`sudo docker build whatsapp-proxy/proxy/ -e PUBLIC_IP=x.x.x.x -t whatsapp_proxy:1.0`

if yes, please close the PR. Thanks. :)

**Comment by matinzd** [comment]
@nimeshkasun Yes. Try and see if that works.

**Comment by nimeshkasun** [comment]
Hi @matinzd,
it didn't work with `docker build` command.

Then I tried with `docker run` like below, and it worked!
`sudo docker run -e PUBLIC_IP=x.x.x.x -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0`

Your suggestion is easy rather than modifying the docker file itself. Thanks again. 
Closing the issue since you solved my concern.

**Pull request closed without merging**
