### PR TITLE
Add README for chart deployment and values override files for EKS and GKE

### PR DESCRIPTION
**Pull request by arashn**
In this PR, I add a README with detailed instructions for creating a Kubernetes cluster on Amazon EKS and Google Kubernetes Engine (GKE). I also include values override files with appropriate configuration changes for deploying to EKS and GKE.

The instructions and the values override files for EKS and GKE have all been tested and verified to make sure that the end result works as a proxy.

### CODE REVIEW

**Comment by slawlor** [comment]
due to the image being pulled, let's wait on #114 to be merged in first, but thanks for the contribution!

**Review by Mitsuecom — APPROVED** [review]

**Review by sabir-8 — APPROVED** [review]

**Comment by arashn** [comment]
@slawlor  the Docker image build is failing because of missing username and password. Is there anything I need to add?

**Review by Rezaluky — APPROVED** [review]

**Comment by slawlor** [comment]
> @slawlor the Docker image build is failing because of missing username and password. Is there anything I need to add?

Sorry for the delay, it's because you're not a maintainer/contributor. Github doesn't seem to allow the secrets to be accessed outside of those scenarios. It's fine I think. There's nothing here that'd impact the docker build, so I'm going to approve this

**Review by slawlor — APPROVED** [review]

**Review by LAVANWIJESIRIWARDANA — APPROVED** [review]

**Pull request merged**
