### PR TITLE
Add values override file for Amazon EKS deployments

### PR DESCRIPTION
**Pull request by arashn**

### CODE REVIEW

**Comment by slawlor** [comment]
Can you please explain why you feel this is necessary to include? And outline what you're doing in the PR please

**Comment by arashn** [comment]
This PR adds annotations for the ingress resource specific to the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller). It is meant to aid deployments to Amazon's EKS service. It is was not intended to be part of the core project. Rather, it was intended to be more like an example values override, to help with necessary configuration changes when deploying to EKS.

**Comment by slawlor** [comment]
> This PR adds annotations for the ingress resource specific to the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller). It is meant to aid deployments to Amazon's EKS service. It is was not intended to be part of the core project. Rather, it was intended to be more like an example values override, to help with necessary configuration changes when deploying to EKS.

Can you add that as a comment to the file? We don't want people to misunderstand that we're forcing AWS for example.

**Comment by arashn** [comment]
I have updated the values override file to include the notes as comments in the file, and also corrected some configuration parameters. It turned out that ingress was not necessary to be deployed to EKS for the deployment to work correctly, and as such I removed it from this file.

**Comment by arashn** [comment]
Also, I was thinking that actually it would be a better idea to include a README with detailed instructions for deploying to EKS, rather than just having this override file here. If you prefer, I can work on adding such a readme and close this PR and resubmit another PR with all files together.

**Comment by slawlor** [comment]
> Also, I was thinking that actually it would be a better idea to include a README with detailed instructions for deploying to EKS, rather than just having this override file here. If you prefer, I can work on adding such a readme and close this PR and resubmit another PR with all files together.

I think this would be helpful, we can make something like a deployments folder specific to various infra's. Thanks.

**Comment by arashn** [comment]
Sounds good. Closing this PR for now.

**Pull request closed without merging**
