### PR TITLE
Added explicit file ending to sh files

### PR DESCRIPTION
**Pull request by abubakrsiddq**
This is with reference to https://github.com/WhatsApp/proxy/issues/64

When repo is clone, sometimes the line ending cause problems during docker build, so I have added gitattributes to define line ending on the sh files explicitly.

Also, I have just added a new line at the end of the .sh file and normalized them.

### CODE REVIEW

**Comment by slawlor** [comment]
Thanks for this! Did you run a re-normalization of the existing files with

```bash
git add --renormalize .
```
?

If you could and update the PR that'd be great, then we can get it merged

**Comment by abubakrsiddq** [comment]
> Thanks for this! Did you run a re-normalization of the existing files with
> 
> ```shell
> git add --renormalize .
> ```
> 
> ?
> 
> If you could and update the PR that'd be great, then we can get it merged

yes ran this

**Review by slawlor — APPROVED** [review]

**Review by Lib7782 — APPROVED** [review]

**Review by shoaib9804725 — CHANGES_REQUESTED** [review]
[]()

**Review by DEMO861 — APPROVED** [review]

**Review by Endricfr — APPROVED** [review]

**Review by Mideee419 — COMMENTED** [review]
Cool

**Pull request merged**
